# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Terraform CI/CD'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository
    - name: Checkout the repository
      uses: actions/checkout@v4

    # Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SECRETS }}

    # Install Checkov
    - name: Install Checkov
      run: |
        python -m pip install --upgrade pip
        pip install checkov
        checkov --version  # Verify Checkov is installed

    # Run Checkov on the code
    - name: Run Checkov
      run: checkov -d . || true

    # Install TFLint
    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint --version  # Verify TFLint is installed

    # Run TFLint to lint Terraform files
    - name: Run TFLint
      run: tflint || true

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Plan Terraform for Dev
    - name: Terraform Plan for Dev
      run: terraform plan -var-file=dev.tfvars -out=tfplan.binary

    # Apply Terraform for Dev
    - name: Terraform Apply for Dev
      run: terraform apply -var-file=dev.tfvars -auto-approve

    # Plan and Apply for QA
    - name: Terraform Plan for QA
      run: terraform plan -var-file=qa.tfvars -out=tfplan.binary

    - name: Terraform Apply for QA
      run: terraform apply -var-file=qa.tfvars -auto-approve

    # Plan and Apply for Prod
    - name: Terraform Plan for Prod
      run: terraform plan -var-file=prod.tfvars -out=tfplan.binary

    - name: Terraform Apply for Prod
      run: terraform apply -var-file=prod.tfvars -auto-approve
